/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2021-11-06 22:10:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>Enroll Course</title>\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("        <meta content=\"eCommerce HTML Template Free Download\" name=\"keywords\">\n");
      out.write("        <meta content=\"eCommerce HTML Template Free Download\" name=\"description\">\n");
      out.write("\n");
      out.write("        <!-- Favicon -->\n");
      out.write("        <link href=\"img/favicon.ico\" rel=\"icon\">\n");
      out.write("\n");
      out.write("        <!-- Google Fonts -->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- CSS Libraries -->\n");
      out.write("        <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"lib/slick/slick.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"lib/slick/slick-theme.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- Template Stylesheet -->\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!-- Top bar Start -->\n");
      out.write("        <div class=\"top-bar\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-6\">\n");
      out.write("                        <i class=\"fa fa-envelope\"></i>\n");
      out.write("                        support@email.com\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-6\">\n");
      out.write("                        <i class=\"fa fa-phone-alt\"></i>\n");
      out.write("                        +012-345-6789\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Top bar End -->\n");
      out.write("        \n");
      out.write("        <!-- Nav Bar Start -->\n");
      out.write("        <div class=\"nav\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\n");
      out.write("                    <a href=\"#\" class=\"navbar-brand\">MENU</a>\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\">\n");
      out.write("                        <div class=\"navbar-nav mr-auto\">\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\">Home</a>\n");
      out.write("                            <a href=\"product-list.html\" class=\"nav-item nav-link\">Products</a>\n");
      out.write("                            <a href=\"product-detail.html\" class=\"nav-item nav-link active\">Product Detail</a>\n");
      out.write("                            <a href=\"cart.html\" class=\"nav-item nav-link\">Cart</a>\n");
      out.write("                            <a href=\"checkout.html\" class=\"nav-item nav-link\">Checkout</a>\n");
      out.write("                            <a href=\"my-account.html\" class=\"nav-item nav-link\">My Account</a>\n");
      out.write("                            <div class=\"nav-item dropdown\">\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">More Pages</a>\n");
      out.write("                                <div class=\"dropdown-menu\">\n");
      out.write("                                    <a href=\"wishlist.html\" class=\"dropdown-item\">Wishlist</a>\n");
      out.write("                                    <a href=\"login.html\" class=\"dropdown-item\">Login & Register</a>\n");
      out.write("                                    <a href=\"contact.html\" class=\"dropdown-item\">Contact Us</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"navbar-nav ml-auto\">\n");
      out.write("                            <div class=\"nav-item dropdown\">\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">User Account</a>\n");
      out.write("                                <div class=\"dropdown-menu\">\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item\">Login</a>\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item\">Register</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Nav Bar End -->      \n");
      out.write("        \n");
      out.write("        <!-- Bottom Bar Start -->\n");
      out.write("        <div class=\"bottom-bar\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row align-items-center\">\n");
      out.write("                    <div class=\"col-md-3\">\n");
      out.write("                        <div class=\"logo\">\n");
      out.write("                            <a href=\"./HomeControl\">\n");
      out.write("                                <img src=\"img/logo.png\" alt=\"Logo\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"search\">\n");
      out.write("                            <input type=\"text\" placeholder=\"Search\">\n");
      out.write("                            <button><i class=\"fa fa-search\"></i></button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-3\">\n");
      out.write("                        <div class=\"user\">\n");
      out.write("                            <a href=\"wishlist.html\" class=\"btn wishlist\">\n");
      out.write("                                <i class=\"fa fa-heart\"></i>\n");
      out.write("                                <span>(0)</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"cart.html\" class=\"btn cart\">\n");
      out.write("                                <i class=\"fa fa-shopping-cart\"></i>\n");
      out.write("                                <span>(0)</span>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Bottom Bar End --> \n");
      out.write("        \n");
      out.write("        <!-- Breadcrumb Start -->\n");
      out.write("        <div class=\"breadcrumb-wrap\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <ul class=\"breadcrumb\">\n");
      out.write("                    <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\n");
      out.write("                    <li class=\"breadcrumb-item\"><a href=\"#\">Products</a></li>\n");
      out.write("                    <li class=\"breadcrumb-item active\">Product Detail</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Breadcrumb End -->\n");
      out.write("        \n");
      out.write("        <!-- Product Detail Start -->\n");
      out.write("        <div class=\"product-detail\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <div class=\"product-detail-top\">\n");
      out.write("                            <div class=\"row align-items-center\">\n");
      out.write("                                <div class=\"col-md-5\">\n");
      out.write("                                    \n");
      out.write("                                    <div class=\"product-slider-single normal-slider\">\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Product Image\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-7\">\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"title\"><h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1></div>\n");
      out.write("                                        <p>\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                        </p>\n");
      out.write("                                     \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"row product-detail-bottom\">\n");
      out.write("                            <div class=\"col-lg-12\">\n");
      out.write("                               \n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                      \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("        <!-- Product Detail End -->\n");
      out.write("        \n");
      out.write("        <!-- Brand Start -->\n");
      out.write("        <!-- Brand End -->\n");
      out.write("        \n");
      out.write("        <!-- Footer Start -->\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                        <div class=\"footer-widget\">\n");
      out.write("                            <h2>Get in Touch</h2>\n");
      out.write("                            <div class=\"contact-info\">\n");
      out.write("                                <p><i class=\"fa fa-map-marker\"></i>123 E Store, Los Angeles, USA</p>\n");
      out.write("                                <p><i class=\"fa fa-envelope\"></i>email@example.com</p>\n");
      out.write("                                <p><i class=\"fa fa-phone\"></i>+123-456-7890</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                        <div class=\"footer-widget\">\n");
      out.write("                            <h2>Follow Us</h2>\n");
      out.write("                            <div class=\"contact-info\">\n");
      out.write("                                <div class=\"social\">\n");
      out.write("                                    <a href=\"\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                                    <a href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                                    <a href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("                                    <a href=\"\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                                    <a href=\"\"><i class=\"fab fa-youtube\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                        <div class=\"footer-widget\">\n");
      out.write("                            <h2>Company Info</h2>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"#\">About Us</a></li>\n");
      out.write("                                <li><a href=\"#\">Privacy Policy</a></li>\n");
      out.write("                                <li><a href=\"#\">Terms & Condition</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                        <div class=\"footer-widget\">\n");
      out.write("                            <h2>Purchase Info</h2>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"#\">Pyament Policy</a></li>\n");
      out.write("                                <li><a href=\"#\">Shipping Policy</a></li>\n");
      out.write("                                <li><a href=\"#\">Return Policy</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"row payment align-items-center\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"payment-method\">\n");
      out.write("                            <h2>We Accept:</h2>\n");
      out.write("                            <img src=\"img/payment-method.png\" alt=\"Payment Method\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"payment-security\">\n");
      out.write("                            <h2>Secured By:</h2>\n");
      out.write("                            <img src=\"img/godaddy.svg\" alt=\"Payment Security\" />\n");
      out.write("                            <img src=\"img/norton.svg\" alt=\"Payment Security\" />\n");
      out.write("                            <img src=\"img/ssl.svg\" alt=\"Payment Security\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Footer End -->\n");
      out.write("        \n");
      out.write("        <!-- Footer Bottom Start -->\n");
      out.write("        <div class=\"footer-bottom\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6 copyright\">\n");
      out.write("                        <p>Copyright &copy; <a href=\"https://htmlcodex.com\">HTML Codex</a>. All Rights Reserved</p>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-6 template-by\">\n");
      out.write("                        <p>Template By <a href=\"https://htmlcodex.com\">HTML Codex</a></p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Footer Bottom End -->       \n");
      out.write("        \n");
      out.write("        <!-- Back to Top -->\n");
      out.write("        <a href=\"#\" class=\"back-to-top\"><i class=\"fa fa-chevron-up\"></i></a>\n");
      out.write("        \n");
      out.write("        <!-- JavaScript Libraries -->\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <script src=\"lib/easing/easing.min.js\"></script>\n");
      out.write("        <script src=\"lib/slick/slick.min.js\"></script>\n");
      out.write("        \n");
      out.write("        <!-- Template Javascript -->\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
