/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2021-07-15 05:14:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HomePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n");
      out.write("    <title>Edunet.vn</title>\n");
      out.write("    <link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600\"\n");
      out.write("    />\n");
      out.write("    <!-- https://fonts.google.com/specimen/Open+Sans -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/all.min.css\" />\n");
      out.write("    <!-- https://fontawesome.com/ -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("    <!-- https://getbootstrap.com/ -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/tooplate-style.css\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container\" id=\"home\">\n");
      out.write("      <div class=\"col-12 text-center\">\n");
      out.write("        <div class=\"tm-page-header\">\n");
      out.write("          <i class=\"fas fa-4x fa-chart-bar mr-4\"></i>\n");
      out.write("          \n");
      out.write("          <h1 class=\"d-inline-block text-uppercase\">EDUNET</h1>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- navbar -->\n");
      out.write("    <form class=\"form-signin\" action=\"login\" method=\"post\">\n");
      out.write("    <div class=\"tm-nav-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-12\">\n");
      out.write("            <nav class=\"navbar navbar-expand-md navbar-light\">\n");
      out.write("              <button\n");
      out.write("                class=\"navbar-toggler\"\n");
      out.write("                type=\"button\"\n");
      out.write("                data-toggle=\"collapse\"\n");
      out.write("                data-target=\"#tmMainNav\"\n");
      out.write("                aria-controls=\"tmMainNav\"\n");
      out.write("                aria-expanded=\"false\"\n");
      out.write("                aria-label=\"Toggle navigation\"\n");
      out.write("              >\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("              </button>\n");
      out.write("\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"tmMainNav\">\n");
      out.write("               <a href=\"#\"> <img src=\"img/logo.png\" alt=\"HomePage\" height=\"70px\"> </a> \n");
      out.write("                <ul class=\"navbar-nav mx-auto tm-navbar-nav\">\n");
      out.write("                  <li class=\"nav-item active\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#home\"\n");
      out.write("                      >Home <span class=\"sr-only\">(current)</span></a\n");
      out.write("                    >\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"home\">Courses</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">About Us</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Contact</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"Login.jsp\">Login</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link external\" href=\"https://www.facebook.com/templatemo\"></a>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("    <!-- Video Banner -->\n");
      out.write("    <section class=\"tm-banner-section\" id=\"tmVideoSection\">\n");
      out.write("      <div class=\"container tm-banner-text-container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-12\">\n");
      out.write("            <header>\n");
      out.write("              <h2 class=\"tm-banner-title\">EDUNET</h2>\n");
      out.write("              <p class=\"mx-auto tm-banner-subtitle\">\n");
      out.write("                We provide you the best online courses on every Subject you need.\n");
      out.write("              </p>\n");
      out.write("              <a href=\"Register.jsp\"> <button type=\"submit\" class=\"btn tm-btn tm-btn-big\"> \n");
      out.write("                Register Now\n");
      out.write("              </button>\n");
      out.write("            </a>\n");
      out.write("            </header>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Video -->\n");
      out.write("      <video id=\"hero-vid\" autoplay=\"\" loop=\"\" muted>\n");
      out.write("        <source src=\"videos/city-night-blur-01.mp4\" type=\"video/mp4\" />\n");
      out.write("        Your browser does not support the video tag.\n");
      out.write("      </video>\n");
      out.write("    </section>\n");
      out.write("    <!-- Features -->\n");
      out.write("    <div class=\"container tm-features-section\" id=\"features\">\n");
      out.write("      <div class=\"row tm-features-row\">\n");
      out.write("        <section class=\"col-md-6 col-sm-12 tm-feature-block\">\n");
      out.write("          <header class=\"tm-feature-header\">\n");
      out.write("            <i class=\"fas fa-5x fa-user-graduate\"></i>\n");
      out.write("            <h3 class=\"tm-feature-h\">Cras pretium diam ut metus</h3>\n");
      out.write("          </header>\n");
      out.write("          <p>\n");
      out.write("            Pro Line HTML5 Template is brought to you by\n");
      out.write("            <a rel=\"nofollow noopener\" href=\"https://www.tooplate.com\"\n");
      out.write("              >Tooplate</a\n");
      out.write("            >. This layout used Bootstrap v4.1.3 UI kit. You can easily modify\n");
      out.write("            this template in any HTML editor for your site.\n");
      out.write("          </p>\n");
      out.write("          <p>\n");
      out.write("            Sed interdum, purus vulputate congue luctus, lorem massa dignissim\n");
      out.write("            nisi, sed condimentum nibh lorem quis lorem. Nulla sed erat\n");
      out.write("            dignissim, tincidunt ante ac, egestas turpis.\n");
      out.write("          </p>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"col-md-6 col-sm-12 tm-feature-block\">\n");
      out.write("          <header class=\"tm-feature-header\">\n");
      out.write("            <i class=\"fas fa-5x fa-graduation-cap\"></i>\n");
      out.write("            <h3 class=\"tm-feature-h\">Cras pretium diam ut metus</h3>\n");
      out.write("          </header>\n");
      out.write("          <p>\n");
      out.write("            Phasellus tristique, sapien quis mattis pellentesque, felis turpis\n");
      out.write("            placerat turpis, nec viverra quam nisl at velit. Pellentesque\n");
      out.write("            iaculis convallis egestas.\n");
      out.write("          </p>\n");
      out.write("          <p>\n");
      out.write("            Nunc ut elit eget velit mollis sodales. Ut non mauris ut ligula\n");
      out.write("            mattis consectetur. Aenean augue arcu, rhoncus at nibh nec, lacinia\n");
      out.write("            blandit nulla.\n");
      out.write("          </p>\n");
      out.write("        </section>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Activities -->\n");
      out.write("    <div class=\"container\" id=\"activities\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-12\">\n");
      out.write("          <div class=\"tm-parallax\">\n");
      out.write("            <header class=\"tm-parallax-header\">\n");
      out.write("              <h2 class=\"\">Courses</h2>\n");
      out.write("            </header>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-6\">\n");
      out.write("          <div class=\"tm-activity-block\">\n");
      out.write("            <div class=\"tm-activity-img-container\">\n");
      out.write("              <img src=\"img/mathematic.png\" width=\"180px\" height=\"190px\" alt=\"Image\" class=\"tm-activity-img\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tm-activity-block-text\">\n");
      out.write("              <h3 class=\"tm-text-blue\">Mathematics</h3>\n");
      out.write("              <p>\n");
      out.write("                In this course, you are going to learn a lot about mathematic. No matter what grade you're on, we have every Math program for you\n");
      out.write("                provided by some famous Mathematician\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6\">\n");
      out.write("          <div class=\"tm-activity-block mr-lg-0 ml-lg-auto\">\n");
      out.write("            <div class=\"tm-activity-img-container\">\n");
      out.write("              <img src=\"img/literature.jpg\" width=\"180px\" height=\"180px\" alt=\"Image\" class=\"tm-activity-img\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tm-activity-block-text\">\n");
      out.write("              <h3 class=\"tm-text-blue\">Literature</h3>\n");
      out.write("              <p>\n");
      out.write("                You are weak at Literature ? You want to get to know more about every works of Literature ? Then welcome, this courses will \n");
      out.write("                give you anything you need to know.\n");
      out.write("                \n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6\">\n");
      out.write("          <div class=\"tm-activity-block\">\n");
      out.write("            <div class=\"tm-activity-img-container\">\n");
      out.write("              <img src=\"img/Branches-of-Physics-1.png\" width=\"180px\" height=\"180px\" alt=\"Image\" class=\"tm-activity-img\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tm-activity-block-text\">\n");
      out.write("              <h3 class=\"tm-text-blue\">Physics</h3>\n");
      out.write("              <p>\n");
      out.write("                Physics is the branch of science that deals with the structure of matter and how \n");
      out.write("                the fundamental constituents of the universe interact.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6\">\n");
      out.write("          <div class=\"tm-activity-block mr-lg-0 ml-lg-auto\">\n");
      out.write("            <div class=\"tm-activity-img-container\">\n");
      out.write("              <img src=\"img/chemistry.jpg\" alt=\"Image\" width=\"180px\" height=\"180px\" class=\"tm-activity-img\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tm-activity-block-text\">\n");
      out.write("              <h3 class=\"tm-text-blue\">Chemistry</h3>\n");
      out.write("              <p>\n");
      out.write("                Chemistry is the study of matter and the changes it undergoes. \n");
      out.write("                Here you can browse chemistry videos, articles, and exercises by topic\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <section class=\"container tm-company-section\" id=\"company\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-xl-9 col-lg-8 col-md-12 tm-company-left\">\n");
      out.write("          <div class=\"tm-company-about\">\n");
      out.write("            <div class=\"tm-company-img-container\">\n");
      out.write("              <img src=\"img/img-05.jpg\" alt=\"Image\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tm-company-about-text\">\n");
      out.write("              <header>\n");
      out.write("                <h2 class=\"tm-company-about-header\">About Us</h2>\n");
      out.write("              </header>\n");
      out.write("              <p>\n");
      out.write("                We are a group of students from FPT University trying to create a platform for everyone to learn freely\n");
      out.write("              </p>\n");
      out.write("              <p class=\"mb-4\">\n");
      out.write("                Here we provide you courses to learn what ever you want to learn \n");
      out.write("              </p>\n");
      out.write("              <a href=\"#\" class=\"btn tm-btn tm-float-right\">Read More</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div\n");
      out.write("          class=\"col-xl-9 col-lg-4 col-md-12 tm-company-right  ml-lg-auto mr-lg-0\"\n");
      out.write("        >\n");
      out.write("          <div class=\"tm-company-right-inner\">\n");
      out.write("            <ul class=\"nav nav-tabs\" id=\"tmCompanyTab\" role=\"tablist\">\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a\n");
      out.write("                  class=\"nav-link tm-nav-link-border-right active\"\n");
      out.write("                  id=\"vision-tab\"\n");
      out.write("                  data-toggle=\"tab\"\n");
      out.write("                  href=\"#vision\"\n");
      out.write("                  role=\"tab\"\n");
      out.write("                  aria-controls=\"vision\"\n");
      out.write("                  aria-selected=\"true\"\n");
      out.write("                  >Vision</a\n");
      out.write("                >\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a\n");
      out.write("                  class=\"nav-link tm-no-border-right\"\n");
      out.write("                  id=\"mission-tab\"\n");
      out.write("                  data-toggle=\"tab\"\n");
      out.write("                  href=\"#mission\"\n");
      out.write("                  role=\"tab\"\n");
      out.write("                  aria-controls=\"mission\"\n");
      out.write("                  aria-selected=\"false\"\n");
      out.write("                  >Mission</a\n");
      out.write("                >\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"tab-content\" id=\"tmTabContent\">\n");
      out.write("              <div\n");
      out.write("                class=\"tab-pane fade show active\"\n");
      out.write("                id=\"vision\"\n");
      out.write("                role=\"tabpanel\"\n");
      out.write("                aria-labelledby=\"vision-tab\"\n");
      out.write("              >\n");
      out.write("                <li>\n");
      out.write("                  We are planning to make this available for everyone\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  Everyone can access and cost only a little money\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  Become one of the best online learning website\n");
      out.write("                </li>\n");
      out.write("              </div>\n");
      out.write("              <div\n");
      out.write("                class=\"tab-pane fade\"\n");
      out.write("                id=\"mission\"\n");
      out.write("                role=\"tabpanel\"\n");
      out.write("                aria-labelledby=\"mission-tab\"\n");
      out.write("              >\n");
      out.write("                <li>\n");
      out.write("                  Bring you every kind of knowledge you need\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  Make everyone learn better and smarter\n");
      out.write("                </li>\n");
      out.write("                <p>\n");
      out.write("                  ..............\n");
      out.write("                </p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Contact -->\n");
      out.write("    <section class=\"container tm-contact-section\" id=\"contact\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-xl-5 col-lg-6 col-md-12 tm-contact-left\">\n");
      out.write("          <div class=\"tm-contact-form-container ml-auto mr-0\">\n");
      out.write("            <header>\n");
      out.write("              <h2 class=\"tm-contact-header\" >Contact Us</h2>\n");
      out.write("            </header>\n");
      out.write("            <form action=\"index.html\" class=\"tm-contact-form\" method=\"POST\">\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <input\n");
      out.write("                  type=\"text\"\n");
      out.write("                  id=\"contact_name\"\n");
      out.write("                  name=\"contact_name\"\n");
      out.write("                  class=\"form-control\"\n");
      out.write("                  placeholder=\"Name\"\n");
      out.write("                  required\n");
      out.write("                />\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <input\n");
      out.write("                  type=\"email\"\n");
      out.write("                  id=\"contact_email\"\n");
      out.write("                  name=\"contact_email\"\n");
      out.write("                  class=\"form-control\"\n");
      out.write("                  placeholder=\"Email\"\n");
      out.write("                  required\n");
      out.write("                />\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <textarea\n");
      out.write("                  rows=\"5\"\n");
      out.write("                  id=\"contact_message\"\n");
      out.write("                  name=\"contact_message\"\n");
      out.write("                  class=\"form-control\"\n");
      out.write("                  placeholder=\"Message\"\n");
      out.write("                  required\n");
      out.write("                ></textarea>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"tm-text-right\">\n");
      out.write("                <button type=\"submit\" class=\"btn tm-btn tm-btn-big\">\n");
      out.write("                  Send It\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-xl-7 col-lg-6 col-md-12 tm-contact-right\">\n");
      out.write("          <div class=\"tm-contact-figure-block\">\n");
      out.write("            <figure class=\"d-inline-block\">\n");
      out.write("              <img src=\"img/img-08.jpg\" alt=\"Image\" width=\"600px\" height=\"400px\"  class=\"img-fluid\" />\n");
      out.write("              <figcaption class=\"tm-contact-figcaption\">\n");
      out.write("                Teach the world online and create an online video course, reach students across the globe, and earn money\n");
      out.write("              </figcaption>\n");
      out.write("            </figure>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <footer class=\"container tm-footer\">\n");
      out.write("      <div class=\"row tm-footer-row\">\n");
      out.write("        <p class=\"col-md-10 col-sm-12 mb-0\">\n");
      out.write("          Copyright &copy; 2018 EDUNET - Design:\n");
      out.write("          <a rel=\"nofollow\" href=\"https://www.facebook.com/tooplate\" class=\"tm-footer-link\">Tooplate</a>\n");
      out.write("        </p>\n");
      out.write("        <div class=\"col-md-2 col-sm-12 scrolltop\">\n");
      out.write("          <div class=\"scroll icon\"><i class=\"fa fa-4x fa-angle-up\"></i></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script src=\"js/jquery-1.9.1.min.js\"></script>\n");
      out.write("    <!-- Single Page Nav plugin works with this version of jQuery -->\n");
      out.write("    <script src=\"js/jquery.singlePageNav.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("      /**\n");
      out.write("       * detect IE\n");
      out.write("       * returns version of IE or false, if browser is not Internet Explorer\n");
      out.write("       */\n");
      out.write("      function detectIE() {\n");
      out.write("        var ua = window.navigator.userAgent;\n");
      out.write("\n");
      out.write("        var msie = ua.indexOf(\"MSIE \");\n");
      out.write("        if (msie > 0) {\n");
      out.write("          // IE 10 or older => return version number\n");
      out.write("          return parseInt(ua.substring(msie + 5, ua.indexOf(\".\", msie)), 10);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var trident = ua.indexOf(\"Trident/\");\n");
      out.write("        if (trident > 0) {\n");
      out.write("          // IE 11 => return version number\n");
      out.write("          var rv = ua.indexOf(\"rv:\");\n");
      out.write("          return parseInt(ua.substring(rv + 3, ua.indexOf(\".\", rv)), 10);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // var edge = ua.indexOf('Edge/');\n");
      out.write("        // if (edge > 0) {\n");
      out.write("        //     // Edge (IE 12+) => return version number\n");
      out.write("        //     return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);\n");
      out.write("        // }\n");
      out.write("\n");
      out.write("        // other browser\n");
      out.write("        return false;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      function setVideoHeight() {\n");
      out.write("        const videoRatio = 1920 / 1080;\n");
      out.write("        const minVideoWidth = 400 * videoRatio;\n");
      out.write("        let secWidth = 0,\n");
      out.write("          secHeight = 0;\n");
      out.write("\n");
      out.write("        secWidth = videoSec.width();\n");
      out.write("        secHeight = videoSec.height();\n");
      out.write("\n");
      out.write("        secHeight = secWidth / 2.13;\n");
      out.write("\n");
      out.write("        if (secHeight > 600) {\n");
      out.write("          secHeight = 600;\n");
      out.write("        } else if (secHeight < 400) {\n");
      out.write("          secHeight = 400;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (secWidth > minVideoWidth) {\n");
      out.write("          $(\"video\").width(secWidth);\n");
      out.write("        } else {\n");
      out.write("          $(\"video\").width(minVideoWidth);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        videoSec.height(secHeight);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      // Parallax function\n");
      out.write("      // https://codepen.io/roborich/pen/wpAsm\n");
      out.write("      var background_image_parallax = function($object, multiplier) {\n");
      out.write("        multiplier = typeof multiplier !== \"undefined\" ? multiplier : 0.5;\n");
      out.write("        multiplier = 1 - multiplier;\n");
      out.write("        var $doc = $(document);\n");
      out.write("        $object.css({ \"background-attatchment\": \"fixed\" });\n");
      out.write("        $(window).scroll(function() {\n");
      out.write("          var from_top = $doc.scrollTop(),\n");
      out.write("            bg_css = \"center \" + multiplier * from_top + \"px\";\n");
      out.write("          $object.css({ \"background-position\": bg_css });\n");
      out.write("        });\n");
      out.write("      };\n");
      out.write("\n");
      out.write("      $(window).scroll(function() {\n");
      out.write("        if ($(this).scrollTop() > 50) {\n");
      out.write("          $(\".scrolltop:hidden\")\n");
      out.write("            .stop(true, true)\n");
      out.write("            .fadeIn();\n");
      out.write("        } else {\n");
      out.write("          $(\".scrolltop\")\n");
      out.write("            .stop(true, true)\n");
      out.write("            .fadeOut();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // Make sticky header\n");
      out.write("        if ($(this).scrollTop() > 158) {\n");
      out.write("          $(\".tm-nav-section\").addClass(\"sticky\");\n");
      out.write("        } else {\n");
      out.write("          $(\".tm-nav-section\").removeClass(\"sticky\");\n");
      out.write("        }\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      let videoSec;\n");
      out.write("\n");
      out.write("      $(function() {\n");
      out.write("        if (detectIE()) {\n");
      out.write("          alert(\n");
      out.write("            \"Please use the latest version of Edge, Chrome, or Firefox for best browsing experience.\"\n");
      out.write("          );\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        const mainNav = $(\"#tmMainNav\");\n");
      out.write("        mainNav.singlePageNav({\n");
      out.write("          filter: \":not(.external)\",\n");
      out.write("          offset: $(\".tm-nav-section\").outerHeight(),\n");
      out.write("          updateHash: true,\n");
      out.write("          beforeStart: function() {\n");
      out.write("            mainNav.removeClass(\"show\");\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        videoSec = $(\"#tmVideoSection\");\n");
      out.write("\n");
      out.write("        // Adjust height of video when window is resized\n");
      out.write("        $(window).resize(function() {\n");
      out.write("          setVideoHeight();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        setVideoHeight();\n");
      out.write("\n");
      out.write("        $(window).on(\"load scroll resize\", function() {\n");
      out.write("          var scrolled = $(this).scrollTop();\n");
      out.write("          var vidHeight = $(\"#hero-vid\").height();\n");
      out.write("          var offset = vidHeight * 0.6;\n");
      out.write("          var scrollSpeed = 0.25;\n");
      out.write("          var windowWidth = window.innerWidth;\n");
      out.write("\n");
      out.write("          if (windowWidth < 768) {\n");
      out.write("            scrollSpeed = 0.1;\n");
      out.write("            offset = vidHeight * 0.5;\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          $(\"#hero-vid\").css(\n");
      out.write("            \"transform\",\n");
      out.write("            \"translate3d(-50%, \" + -(offset + scrolled * scrollSpeed) + \"px, 0)\"\n");
      out.write("          ); // parallax (25% scroll rate)\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Parallax image background\n");
      out.write("        background_image_parallax($(\".tm-parallax\"), 0.4);\n");
      out.write("\n");
      out.write("        // Back to top\n");
      out.write("        $(\".scroll\").click(function() {\n");
      out.write("          $(\"html,body\").animate(\n");
      out.write("            { scrollTop: $(\"#home\").offset().top },\n");
      out.write("            \"1000\"\n");
      out.write("          );\n");
      out.write("          return false;\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
